name: Deploy Django Project to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/jewellery
            workon jewellery
            git pull origin main
            pip install -r requirements.txt
            python3 manage.py makemigrations
            python3 manage.py migrate
            python3 manage.py collectstatic --noinput
            sudo systemctl restart uwsgi
            sudo systemctl restart nginx
          EOF
